### ISSUE TITLE
How to set progress.setPointerIcon

### ISSUE THREAD

**Issue by AhmadullahSaikat** [tankery/CircularSeekBar#12]
There have the options to set Pointer Color from progress.setPointerColor(0xfffff000);

But how to set progress.setPointerIcon

**Comment by tankery** [comment]
Hi, @AhmadullahSaikat ,

This library currently not support custom drawable for pointer, maybe you can modify the library for your own version, and replace the pointer drawing code in `onDraw` to your own code. You may also need to manage the view's height and width. Please check out #14 for details. Thanks.
