### ISSUE TITLE
Best way to add progressDirection (counter clockwise) 

### ISSUE THREAD

**Issue by Beardsome** [tankery/CircularSeekBar#15]
Hi, 

I'm trying to find out the best solution to set the progress direction either clockwise (like now) or counter clockwise.  Any Tips what part of the CircularSeekBar Code I have to update or change?

**Comment by JonathanImperato** [comment]
Try to enable negative

**Comment by tankery** [comment]
Hi, @Beardsome.
If your requirement is to have progress in both direction, set `app:cs_negative_enabled` in xml file or `CircularSeekBar. setNegativeEnabled(true)` to enable the negative progress is the solution.
But if what you need is just want to limit to a single direction, but in counter clockwise, I think maybe you can "flip" the view by set the `scaleX` to -1.
