### ISSUE TITLE
How can i increase pointer radius to show progress over the pointer?

### ISSUE THREAD

**Issue by saravanan72** [tankery/CircularSeekBar#2]
Hi,
 i just learning the custom views by doing changes and updates. can you tell me how to increase pointer redius to show the progress in pointer. please! am trying many ways, the text , i put that. but in between the short width and height, the text showing overlape amoung them... can u explain me please :)

**Comment by tankery** [comment]
Do you mean you trying to add a number text on the pointer? If so, I'll say that this is not a supported feature for this library. You need to learn and modify the source code to doing so.
