### ISSUE TITLE
Problem when set app:cs_max and app:cs_progress

### ISSUE THREAD

**Issue by dDHuy2908** [tankery/CircularSeekBar#21]
I am using your library to make a music player app. And i got trouble when use app:cs_max and app:cs_progress while using data binding
`Cannot find a setter for \u003cme.tankery.lib.circularseekbar.CircularSeekBar app:cs_max\u003e that accepts parameter type \u0027java.lang.Integer\u0027\n\nIf a binding adapter provides the setter, check that the adapter is annotated correctly and that the parameter type matches.`
How can I solve this problem?
Thanks!

**Comment by tankery** [comment]
Sorry I'm not familiar with data banding currently, can't help on this. Maybe you could try read the source code or ask on StackOverflow?
