### ISSUE TITLE
Color spread issue

### ISSUE THREAD

**Issue by tree1891** [tankery/CircularSeekBar#22]
![circle](https://user-images.githubusercontent.com/1282201/74218389-f4b55380-4ce4-11ea-95ba-ca0d0e66cb24.jpg)

**Comment by AlessandroCignolini** [comment]
i think you just need to put this tag and you will fix it
app:cs_disable_progress_glow = "true"

**Comment by tankery** [comment]
Thanks @AlessandroCignolini ! that will fix this issue.
But yes this is a bug when you enable glow effect for this view, will fix it.
