### ISSUE TITLE
Circular progressbar crashed

### ISSUE THREAD

**Issue by gopi4edu** [tankery/CircularSeekBar#24]
I am notable to get progress value.
In             override fun onProgressChanged(
                circularSeekBar: CircularSeekBar?,
                progress: Float,
                fromUser: Boolean
            ) {

            }
I am trying to show toast but app getting crashed.

**Comment by tankery** [comment]
@gopi4edu could you please paste the crash stack here? thanks.

**Comment by tankery** [comment]
Close for now, please reopen if it is still a problem.
