### ISSUE TITLE
Using gradient color for progress. 

### ISSUE THREAD

**Issue by FECHNOLOGIES** [tankery/CircularSeekBar#27]
Wonderful library. 
Can one use gradient color for the progress?
Thanks

**Comment by tankery** [comment]
Thanks for using this lib, but unfortunately it not support a gradient color yet.

You can try to clone and modify the code, by set a gradient to `mCircleProgressPaint` to implement the gradient color.
And I may consider this feature request in future version. Thanks!

**Comment by FECHNOLOGIES** [comment]
OK.
 Will try looking into it.
