### ISSUE TITLE
Implement incrementProgressBy for move step by step?

### ISSUE THREAD

**Issue by webserveis** [tankery/CircularSeekBar#3]
Please add feature incrementProgressBy ()

Example

.setMax(8);
.incrementProgressBy(1);

I solved this feature, using Math.floor() and force change progress value:

if progress is 0.3 up to 1
if progress is 3.4 up to 4
....

        seekBar.setOnSeekBarChangeListener(new CircularSeekBar.OnCircularSeekBarChangeListener() {
            @Override
            public void onProgressChanged(CircularSeekBar circularSeekBar, float progress, boolean fromUser) {
                String message = String.format("Progress changed to %.2f, fromUser %s", progress, fromUser);
                Log.d("Main", message);
                if (progress>0) circularSeekBar.setProgress( (float) Math.floor(progress));
            }
    }

**Comment by tankery** [comment]
You can manage the progress change by yourself, seems there is no strong reason to add this feature in library.
