### ISSUE TITLE
How can the direction of the progress bar be counterclockwise? I see a counterclockwise preview in the example, but according to the example, it is actually not like this.

### ISSUE THREAD

**Issue by weizhizhu** [tankery/CircularSeekBar#30]
How can the direction of the progress bar be counterclockwise? I see a counterclockwise preview in the example, but according to the example, it is actually not like this.

**Comment by weizhizhu** [comment]
![2021-03-12_15-42](https://user-images.githubusercontent.com/16060581/110908332-9fb19a00-8349-11eb-9b0d-a2fa197ced98.png)

**Comment by weizhizhu** [comment]
Like the above two, their directions are completely different

**Comment by tankery** [comment]
Hey, @weizhizhu The example show a case to use "negative progress", you could do this by using `setNegativeEnabled`.

But if you are saying that you'd like to have a positive progress with counterclockwise bar, I might said it's not supported by this view. But you could be able to do this by "flip" the view. using a trick to `setScaleX(-1f)` to the view.

Or, you could just modify the code to do whatever you want.
