### ISSUE TITLE
How Can I Change Step Size

### ISSUE THREAD

**Issue by OGIPLUS** [tankery/CircularSeekBar#31]
I want change a step size on my circular seekbar . How Can I ? Can you be fast ıt's urgen for me

**Comment by tankery** [comment]
Sorry @OGIPLUS that this view can only be scroll smoothly. It can set max progress to any range you like, but not able to do "steps".

**Comment by OGIPLUS** [comment]
ok thx so much .

3 Nis 2021 Cmt 05:01 tarihinde Tankery ***@***.***> şunu
yazdı:
