### ISSUE TITLE
Is there a way to have a semi-circle start in the middle and move negative and positive numbers?

### ISSUE THREAD

**Issue by YrgkenKoutsi** [tankery/CircularSeekBar#33]
Hi,

Is there a way to have a semi-circle start at 0 middle point and move left negative number and right positive numbers.  Using `cs_start_angle` and `cs_end_angle` does the semi circle however I can't set it to start in the middle and use negative numbers.

Any direction of achieving this would be really appreciated.

**Comment by tankery** [comment]
Hey, @YrgkenKoutsi,
It's an interesting idea to set start point in middle. I'm afraid this library itself may hard to support.

But I think you might want to try to set the progress to 50% and pretend this is the "start" point. then manually recalculate the progress by -50. Therefore, the progress 0 will be -50, and progress 100 will be 50. Hope this could help!
