### ISSUE TITLE
Render issue at 360°/max on Andorid 8.0 / O

### ISSUE THREAD

**Issue by steelbytes** [tankery/CircularSeekBar#5]
steps:
* compile sample app (in this repo)
* install on android 8 (have tried emulator and nexus6p)
* drag the pointer on either the 2nd or 3rd examples ('circular, negative enabled' and 'square, negative enabled') 360°

result:
the blue progress highlight follows the pointer while it is dragged 0-359 but disappears when 360 is reached.

note:
works ok on older android (eg 7.0/nougat or 4.4/kitkat etc)

**Comment by tankery** [comment]
Thanks for your feedback, I'll fix this in next release
