### ISSUE TITLE
Text inside the seek bar

### ISSUE THREAD

**Issue by Coehill** [tankery/CircularSeekBar#8]
Is it possible to have text on the inside of the seek bar?

**Comment by tankery** [comment]
Do you mean inside the progress bar or inside the circle?

If you mean inside the progress bar, I'm sorry it can't do that. But you can try to layout a TextView cover the seek bar to implement this effect.

**Comment by Coehill** [comment]
I meant inside the gap in the middle but yeah I could just use a textview to cover it.

**Comment by tankery** [comment]
Good, happy using it :)
