### ISSUE TITLE
Using circle style 'butt' start and end progress are difficult to reach

### ISSUE THREAD

**Issue by CallumCoombes** [tankery/CircularSeekBar#9]
I am having issue with sliding the seekbar to progress 0 or progress 100 (the ends of the seekbar). When I get close to the ends, around 3-5 or 95-97, the seekbar stops tracking my finger and just stops. I can get to 0 or 100 progress, but I have to carefully take a few attempts to slide it into place.

Any ideas what is causing this?

Here is my xml:

`<me.tankery.lib.circularseekbar.CircularSeekBar
            android:id="@+id/wellnessQViewQSeekBar"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:cs_circle_color="@color/white"
            app:cs_circle_progress_color="#02CFD5"
            app:cs_circle_stroke_width="40dp"
            app:cs_circle_style="butt"
            app:cs_end_angle="40"
            app:cs_lock_enabled="false"
            app:cs_max="100"
            app:cs_move_outside_circle="true"
            app:cs_start_angle="90"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />`

**Comment by tankery** [comment]
@CallumCoombes This bug is fixed, you can upgrade library to version 1.1.5, then set `app:cs_lock_enabled="true"` (or remove it to using the default value) to fix it.
